name: Test and build
on:
  push:
    branches: [ development ]
jobs:
  test_js:
    name: Test Extension (JS)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Launch tests
        shell: powershell
        run: |
          npm install
          npm run test:js
          &cmd.exe /c rd /s /q .vscode-test
  test_ts:
    name: Test Extension (TS)
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Launch tests
        run: |
          npm install
          npm run test:ts
          &cmd.exe /c rd /s /q .vscode-test
  test_ws:
    name: Test Extension (Workspaces)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: Launch tests
        run: |
          npm install
          npm run test:ws:multijs
          npm run test:ws:multits
  build_artifact:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - name: npm install and build
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          export PATH=~/.npm-global/bin:$PATH
          npm install
          npm install -g vsce
          vsce package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ui5plugin
          path: |
            *.vsix
