name: Test and build
on:
  push:
    branches: [ development, typescript ]
jobs:
  test:
    name: Test Extension
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3.1
      - name: Launch tests
        run: |
          npm install
          npm run test
          &cmd.exe /c rd /s /q .vscode-test
  build_artifact:
    name: Build Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1
      - name: npm install and build
        env:
          NPM_CONFIG_PREFIX: "~/.npm-global"
        run: |
          export PATH=~/.npm-global/bin:$PATH
          npm install
          npm install -g vsce
          vsce package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: ui5plugin
          path: |
            *.vsix
