name: Test and build
on:
  push:
    branches: [ development ]
jobs:
  test:
    name: Test Extension
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Launch tests
        run: |
          yarn install
          npm run test
  build_artifact:
    name: Build Extension
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          yarn install
          npm install -g vsce
          vsce package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ui5plugin
          path: |
            *.vsix
