name: Test vscode plugin and build artifact
on:
  push:
    branches: [ development ]
jobs:
  test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Launch tests
        run: |
          npm install
          npm test
  build_artifact:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: npm install and build
        run: |
          npm install
          npm install -g vsce
          vsce package
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ui5plugin
          path: |
            *.vsix
