name: Release and deploy
on:
  push:
    branches: [ master ]
jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: package-version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        with:
          tag: v${{ env.PACKAGE_VERSION }}
          name: v${{ env.PACKAGE_VERSION }}
          body: v${{ env.PACKAGE_VERSION }}
          draft: false
          prerelease: false
          makeLatest: true
          generateReleaseNotes: true
  deploy:
    name: Deploy to marketplace
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: npm install
        run: npm install
      - name: deploy
        uses: lannonbr/vsce-action@master
        with:
          args: "publish -p $VSCE_TOKEN"
        env:
          VSCE_TOKEN: ${{ secrets.VSCE_TOKEN }}
  publish_ovsx:
    name: Publish to open vsx
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: npm install
        run: npm install
      - name: publish
        run: npx ovsx publish -p ${{ secrets.OVSX_TOKEN }}